"""add_bs_cf_columns

Revision ID: 041a1e737d98
Revises: 723fcb1a61e6
Create Date: 2026-02-04 01:30:01.584090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '041a1e737d98'
down_revision: Union[str, None] = '723fcb1a61e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_statements', sa.Column('current_assets', sa.BigInteger(), nullable=True))
    op.add_column('financial_statements', sa.Column('current_liabilities', sa.BigInteger(), nullable=True))
    op.add_column('financial_statements', sa.Column('inventories', sa.BigInteger(), nullable=True))
    op.add_column('financial_statements', sa.Column('capex', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_statements', 'capex')
    op.drop_column('financial_statements', 'inventories')
    op.drop_column('financial_statements', 'current_liabilities')
    op.drop_column('financial_statements', 'current_assets')
    # ### end Alembic commands ###
