"""add_per_pbr_columns

Revision ID: a484184bbe77
Revises: 041a1e737d98
Create Date: 2026-02-04 01:46:17.758076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a484184bbe77'
down_revision: Union[str, None] = '041a1e737d98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_statements', sa.Column('per', sa.Float(), nullable=True))
    op.add_column('financial_statements', sa.Column('pbr', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_statements', 'pbr')
    op.drop_column('financial_statements', 'per')
    # ### end Alembic commands ###
